spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  datasource:
    url: jdbc:h2:~/pet_clinic
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
